/**
 * Plain-language explanations of every term the app uses. Each entry says what the
 * term is, how dealerships use it, and what to ask for. Rendered by <Term> popovers
 * and the Glossary page. No marketing copy.
 */

export interface GlossaryEntry {
  key: string;
  term: string;
  short: string;
  what: string;
  dealer: string;
  ask: string;
  related?: string[];
}

export const GLOSSARY: GlossaryEntry[] = [
  {
    key: "total_srp",
    term: "Total SRP",
    short: "The bottom line of the window sticker.",
    what: "Base MSRP plus factory options, delivery (DPH) and, in the Southeast, distributor-installed options. It is the manufacturer's and distributor's suggested price before the dealer touches it.",
    dealer: "Dealers anchor discounts to it ('$3,000 off') while adding fees below the line. The percentage of Total SRP you actually pay all-in is the cleanest way to compare dealers.",
    ask: "Ask for the window sticker and check that the line items add up to the Total SRP.",
    related: ["factory_msrp", "distributor_options", "dph", "all_in"],
  },
  {
    key: "factory_msrp",
    term: "Factory MSRP + DPH",
    short: "The manufacturer's price before distributor and dealer additions.",
    what: "Base MSRP plus factory options plus delivery, processing and handling. Everything the factory shipped, priced by Toyota.",
    dealer: "In Southeast Toyota's region the sticker adds port-installed options on top. A selling price below factory MSRP + DPH means the distributor add-ons were discounted away, which is a strong signal.",
    ask: "Compare your selling price to this number, not just to the Total SRP.",
    related: ["total_srp", "distributor_options"],
  },
  {
    key: "distributor_options",
    term: "Distributor (port) options",
    short: "Accessories installed by the regional distributor before the dealer gets the car.",
    what: "Southeast Toyota and Gulf States Toyota add items such as tires, protection packages, emblems and cross bars at the port and print them on the sticker.",
    dealer: "They are on the sticker, so dealers present them as factory pricing. They are high-margin and often fully discountable.",
    ask: "Treat them as negotiable. Ask for a unit without them or a price that discounts them.",
    related: ["total_srp", "dealer_addons"],
  },
  {
    key: "dph",
    term: "DPH (delivery, processing and handling)",
    short: "The destination charge printed on the sticker.",
    what: "A fixed per-vehicle charge from the manufacturer for shipping. It is the same for every unit of a model.",
    dealer: "Legitimate and not negotiable, but some dealers add a second 'freight' or 'dealer prep' fee that duplicates it.",
    ask: "Pay it once. Refuse any second delivery or prep fee.",
  },
  {
    key: "selling_price",
    term: "Selling price",
    short: "The dealer's price for the vehicle before fees, tax and title.",
    what: "What the dealer is actually charging for the car itself. Discount off Total SRP is Total SRP minus selling price.",
    dealer: "Dealers prefer to talk payment or 'balance' because those hide the selling price. A worksheet that shows no selling price is a warning sign.",
    ask: "Always get the selling price in writing before discussing trade or financing.",
    related: ["all_in", "otd"],
  },
  {
    key: "dealer_fees",
    term: "Dealer fees",
    short: "Charges the dealer adds for its own paperwork.",
    what: "Doc (documentation) fee, electronic lien and title (ELT) fee, and similar. Georgia does not cap doc fees; $500 to $900 is common in Atlanta.",
    dealer: "Usually non-negotiable per dealer policy, but the selling price can be lowered to offset them.",
    ask: "Ask for a lower selling price to cover the doc fee rather than asking to remove the fee.",
    related: ["all_in"],
  },
  {
    key: "dealer_addons",
    term: "Dealer add-ons",
    short: "Anything the dealer added that is not on the window sticker.",
    what: "Tint, nitrogen, VIN etching, paint or fabric protection, 'carbon neutral' programs, market adjustments, pre-installed accessories.",
    dealer: "Often listed on a second sticker or appear only on the worksheet. Margins are very high and they are fully negotiable.",
    ask: "Ask for every add-on removed, or for its full amount taken off the selling price.",
    related: ["junk_fees", "all_in"],
  },
  {
    key: "junk_fees",
    term: "Junk fees",
    short: "Add-ons and fees with little or no value to you.",
    what: "Nitrogen in tires, VIN etch, 'market adjustment', dealer prep, addendum stickers, protection packages priced far above cost.",
    dealer: "They raise the all-in price without changing the car. Some dealers refuse to remove them but will discount the car by the same amount.",
    ask: "Keep a list in Settings; the app flags any line that matches it.",
    related: ["dealer_addons"],
  },
  {
    key: "all_in",
    term: "All-in dealer price",
    short: "Selling price plus every dealer fee and add-on. The number that decides.",
    what: "Everything the dealer controls, added together. Government fees (tax, title, registration) are left out because they are the same at every dealer for the same price.",
    dealer: "Dealers can move money between selling price, fees and add-ons; the all-in total is what they cannot hide.",
    ask: "Compare dealers on all-in as a percentage of Total SRP. Your targets are in Settings.",
    related: ["selling_price", "dealer_fees", "dealer_addons", "otd"],
  },
  {
    key: "otd",
    term: "Out the door (OTD)",
    short: "All-in dealer price plus tax, title and registration.",
    what: "The full cash price to drive away with no trade and no financing.",
    dealer: "An OTD quote is only useful if it is itemized; a single number can hide a tax computed on the wrong base.",
    ask: "Ask for an itemized OTD quote on a specific VIN with no trade and no financing assumptions.",
    related: ["all_in", "tavt"],
  },
  {
    key: "tavt",
    term: "Georgia TAVT",
    short: "Georgia's one-time Title Ad Valorem Tax, 7% at purchase, in place of sales tax.",
    what: "Charged once when the vehicle is titled. For a dealer sale the base is the selling price plus taxable fees minus your trade-in allowance (when the trade's VIN and owner are recorded).",
    dealer: "A common worksheet error is computing TAVT without subtracting the trade, which on a $21,500 trade is a $1,505 overcharge.",
    ask: "Check that the tax line equals 7% of (selling price + taxable fees - trade allowance).",
    related: ["trade_allowance", "otd"],
  },
  {
    key: "trade_allowance",
    term: "Trade allowance",
    short: "What the dealer credits for your current car.",
    what: "The dealer's number for your trade. Your payoff is what you still owe the lender; equity is allowance minus payoff.",
    dealer: "A dealer can raise the allowance while raising the selling price, so nothing changes except the paperwork. The app flags that pattern across revisions.",
    ask: "Negotiate the car's price first, then the trade. Get outside offers (CarMax, Carvana, Tesla) before you talk trade.",
    related: ["equity", "break_even", "outside_offer"],
  },
  {
    key: "equity",
    term: "Trade equity",
    short: "Trade allowance minus loan payoff.",
    what: "Positive equity reduces what you finance; negative equity gets rolled into the new loan.",
    dealer: "Negative equity hidden in a payment is a classic move. Ask to see the payoff and allowance separately.",
    ask: "Get a fresh payoff letter with a good-through date.",
    related: ["trade_allowance"],
  },
  {
    key: "break_even",
    term: "Break-even allowance",
    short: "The dealer trade allowance that equals an outside offer after the tax credit.",
    what: "In Georgia a trade-in reduces TAVT by 7% of the allowance, so a dealer allowance is worth 7% more than the same cash from an outside buyer. Break-even = outside offer / 1.07.",
    dealer: "Dealers lean on the tax credit to justify a low allowance. The credit is real, but it is capped at 7% of the allowance.",
    ask: "If the dealer is below break-even, sell outside or ask them to match.",
    related: ["trade_allowance", "outside_offer", "tavt"],
  },
  {
    key: "outside_offer",
    term: "Outside offer",
    short: "A cash offer for your trade from someone other than the dealer.",
    what: "CarMax, Carvana, Tesla trade-in, a private buyer. Each has an expiry and may be contingent on inspection.",
    dealer: "Having one in hand sets the floor for the dealer's allowance.",
    ask: "Collect two or three, note the expiry dates, and keep them current.",
    related: ["break_even"],
  },
  {
    key: "rebate",
    term: "Manufacturer rebate",
    short: "Money from Toyota (not the dealer) that should come off on top of the negotiated price.",
    what: "Customer cash, college graduate, military and loyalty programs. Some require financing through Toyota Financial Services; some cannot be combined with a special APR.",
    dealer: "Dealers sometimes fold a rebate into the 'discount' so it looks like their generosity. The app flags a rebate marked as inside the price.",
    ask: "Negotiate the price first, then apply rebates after. Tick the programs you qualify for in Settings so the app can tell you when one is missing.",
    related: ["conditional_rebate"],
  },
  {
    key: "conditional_rebate",
    term: "Conditional rebate",
    short: "A rebate with strings attached.",
    what: "Tied to financing with TFS, to a graduation date, to military status, or to trading in a competitor's car.",
    dealer: "The condition is where the money hides: a $500 rebate that requires a 9% APR costs more than it gives.",
    ask: "Compare the deal with and without the condition; the app shows both.",
    related: ["rebate", "apr"],
  },
  {
    key: "apr",
    term: "APR",
    short: "The yearly interest rate on a loan.",
    what: "The payment on a loan is fixed by the principal, the APR and the term. Given any three, the fourth can be solved; the app solves the APR a payment grid implies.",
    dealer: "A payment grid can hide a higher rate, a longer term or extra principal. A quoted payment above what the stated APR produces means hidden money in the loan.",
    ask: "Get pre-approved elsewhere first, then ask the dealer to beat that rate.",
    related: ["payment_grid", "money_factor"],
  },
  {
    key: "payment_grid",
    term: "Payment grid",
    short: "The table of monthly payments by term and cash down on a worksheet.",
    what: "Each cell is a payment for a term and a down payment. The app solves the APR behind every cell and checks that a row agrees with itself.",
    dealer: "Grids are shown instead of the selling price to steer you to a payment you can 'afford'.",
    ask: "Ask what APR and principal the grid assumes, and compare to the computed cells.",
    related: ["apr"],
  },
  {
    key: "money_factor",
    term: "Money factor",
    short: "The lease's interest rate, written as a small decimal.",
    what: "Multiply by 2400 to get the equivalent APR. 0.00250 is 6.0% APR. The rent charge each month is (adjusted cap cost + residual) x money factor.",
    dealer: "Dealers may mark the money factor up above the lessor's 'buy rate' and keep the difference.",
    ask: "Ask for the buy rate. Enter it in Settings so the app can measure the markup.",
    related: ["cap_cost", "residual", "apr"],
  },
  {
    key: "cap_cost",
    term: "Capitalized cost (cap cost)",
    short: "The lease's selling price, plus anything rolled in.",
    what: "Gross cap cost is the agreed value plus capitalized fees. Cap cost reductions (money down, rebates, trade equity) bring it to the adjusted cap cost, which drives the payment.",
    dealer: "The agreed value is as negotiable as a purchase price, but it is rarely shown on a lease worksheet.",
    ask: "Ask for the agreed value and compare it to the best purchase selling price.",
    related: ["money_factor", "residual"],
  },
  {
    key: "residual",
    term: "Residual value",
    short: "What the lessor says the car will be worth at the end of the lease.",
    what: "A percentage of MSRP set by the lessor for a given term and mileage. The payment covers the difference between adjusted cap cost and residual.",
    dealer: "Not negotiable. A dealer cannot change it, but can choose a term or mileage tier with a better residual.",
    ask: "Compare 24, 36 and 39 month tiers and mileage options.",
    related: ["cap_cost", "money_factor"],
  },
  {
    key: "acquisition_fee",
    term: "Acquisition fee",
    short: "The lessor's fee to start the lease.",
    what: "A standard amount set by the lessor, paid at signing or capitalized into the lease.",
    dealer: "Dealers sometimes mark it up above the standard amount.",
    ask: "Ask for the standard fee. Enter it in Settings to let the app check.",
    related: ["disposition_fee"],
  },
  {
    key: "disposition_fee",
    term: "Disposition fee",
    short: "The fee for returning the car at lease end.",
    what: "Charged when you return the vehicle, often waived if you buy it or lease another from the same brand.",
    dealer: "Fixed by the lessor; not a negotiation point.",
    ask: "Count it in the total cost if you plan to return the car.",
    related: ["acquisition_fee"],
  },
  {
    key: "doc_fee",
    term: "Doc fee",
    short: "The dealer's documentation fee.",
    what: "A charge for preparing the paperwork. Georgia has no legal cap.",
    dealer: "Dealers say it is charged to everyone. True, but the selling price can offset it.",
    ask: "Ask for the selling price lowered by the doc fee amount.",
    related: ["dealer_fees"],
  },
  {
    key: "elt",
    term: "ELT fee",
    short: "Electronic lien and title processing fee.",
    what: "A small fee for recording the lender's lien electronically.",
    dealer: "Usually under $50 at cost; $200 or more is a markup.",
    ask: "Question anything well above the state's actual charge.",
    related: ["dealer_fees"],
  },
  {
    key: "lemon_law_fee",
    term: "Lemon law fee",
    short: "Georgia's $3 fee that funds the lemon-law program.",
    what: "A government fee on every new vehicle sale.",
    dealer: "Legitimate and tiny.",
    ask: "Nothing to do.",
  },
  {
    key: "four_square",
    term: "Four-square worksheet",
    short: "The classic dealer worksheet with price, trade, down payment and monthly payment in four boxes.",
    what: "A sales tool that lets the dealer move money between boxes while you watch one of them.",
    dealer: "Lowering the payment by lengthening the term or raising the trade while raising the price are the standard moves.",
    ask: "Ignore the boxes. Settle price, then trade, then financing, each on its own.",
    related: ["selling_price", "trade_allowance", "apr"],
  },
];

export const GLOSSARY_BY_KEY: Record<string, GlossaryEntry> = Object.fromEntries(GLOSSARY.map((g) => [g.key, g]));
